### ISSUE TITLE
Add-on installation failing

### ISSUE THREAD

**Issue by chriscrowe** [sarabveer/rsync-snapshot-backup#2]
Been trying to debug this but hitting a dead end. Any thoughts?

```
Step 4/20 : RUN apk add --no-cache jq sshpass rsync
 ---> Running in 9910da69f3e6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz: temporary error (try again later)

WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armv7/APKINDEX.tar.gz: temporary error (try again later)

ERROR: unsatisfiable constraints:

  rsync (missing):
    required by: world[rsync]
  sshpass (missing):
    required by: world[sshpass]
Removing intermediate container 9910da69f3e6
```

**Comment by chriscrowe** [comment]
I separated out the dependencies to try and root-cause, `jq` seemed install just fine but `sshpass` and `rsync` seem to have this issue when trying to install in Alpine. The error message is not super clear to me.

**Comment by sarabveer** [comment]
Seems like Alpine's package manager `apk` is unable to fetch the repo?

Maybe it's due to being on `armv7`?

**Comment by chriscrowe** [comment]
Yep you're right-- seems Alpine isn't supported on armv7 (eg RPi v4)

https://wiki.alpinelinux.org/wiki/Alpine_on_ARM

I'll figure out a fix-- thanks!

**Comment by chriscrowe** [comment]
The plot thickens-- seems that doc is out of date, arm32v7 is supported according to the Alpine docker hub page:

https://hub.docker.com/_/alpine

Further, I can see the packages used by your add-on available for armv7 here:

https://pkgs.alpinelinux.org/packages?name=sshpass&branch=edge&repo=main&arch=armv7&maintainer=

https://pkgs.alpinelinux.org/packages?name=rsync&branch=edge&repo=main&arch=armv7

Still digging...

**Comment by chriscrowe** [comment]
I've boiled it down to a DNS problem-- but even adding the `hassio` network to the container doesn't seem to make DNS resolve. which is interesting considering another add-on is using the exact same network and DNS config and it resolves hostnames fine. Still digging...

**Comment by chriscrowe** [comment]
Ended up installing a new 64-bit build of the new Hass OS 5.8 release and this worked straight away. I'll close this issue.
